### ISSUE TITLE
5.3 翻译有误

### ISSUE THREAD

**Issue by star-ll** [lin-123/javascript#11]
[5.3](https://github.com/lin-123/javascript#destructuring--object-over-array) 翻译有误
英文原文L“5.3 Use object destructuring for multiple return values, not array destructuring.”
您翻译成“多个返回值用对象的解构，而不是数据解构。”
“array destructuring” 应该翻译成“数组解构”。

**Comment by lin-123** [comment]
好的， 多谢哈
