### ISSUE TITLE
16.3 和 23.10

### ISSUE THREAD

**Issue by MrRetro** [lin-123/Javascript#25]
[16.3](https://github.com/lin-123/javascript#blocks--no-else-return) 最后一个 //good 内的 else 是不是没必要？
```js
// good
function dogs(x) {
  if (x) {
    if (z) {
      return y;
    }
  } else {
    return z;
  }
}
```

[23.10](https://github.com/lin-123/javascript#naming--uppercase) 以下语法不是挺规范的吗？为什么是不友好的呢？难道变量名含义问题？
```js
// bad
export const THING_TO_BE_CHANGED = 'should obviously not be uppercased';
```

**Comment by Seansun1314** [comment]
您好，您的邮件我已收到！

**Comment by lin-123** [comment]
@MrRetro 
> [16.3](https://github.com/lin-123/javascript#blocks--no-else-return) 最后一个 good 内的 else 确实没必要，只是原文中这些写，就直接翻译过来了
```js
// good 更合理的应该是这样
function dogs(x) {
  if (x) {
    if (z) {
      return y;
    }
  } 
  return z;
}
```

> [23.10](https://github.com/lin-123/javascript#naming--uppercase)  
> 
> ```js
> // bad  THING_TO_BE_CHANGED 指的是这里定义的是可变的变量， 不应该用 const 和大写 来命名；
> export const THING_TO_BE_CHANGED = 'should obviously not be uppercased';
> ```

**Comment by Seansun1314** [comment]
您好，您的邮件我已收到！
